name: Auto Export Archi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Xvfb
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xvfb

      - name: Download Archi
        run: |
          wget https://github.com/archimatetool/archi.io/releases/download/5.7.0/Archi-Linux64-5.7.0.tgz
          tar -xzf Archi-Linux64-5.7.0.tgz
          chmod +x Archi/Archi

      - name: Run Archi
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
            ./Archi/Archi -consoleLog \
            -application com.archimatetool.commandline.app \
            -nosplash \
            -model model/archiPKG.archimate \
            -script scripts/export.ajs

      - name: Commit SVG
        run: |

          git config --global user.name "github-actions"

          git config --global user.email "actions@github.com"

          if [ -d "model/diagrams" ]; then

            git add model/diagrams/

            git commit -m "Auto export diagrams" || echo "No changes"

            git push

          else

            echo "Folder diagrams tidak ditemukan, skip commit."

          fi
